language: ruby
rvm:
  - 2.1.1
script:
  - bundle exec rake test
env:
  global:
    secure: GK6xQaAaAgAWH7Xzex6MvwOK3wq0ojL6mHQnYPgljGE834gFuHSQsRFCeFckSCKwLGhLJpUdxpAIwngNDKK2z1AUt+UJWfi7fS5DOG0dTwek+Fn9mU7X5a9GXaYzKTUQAPSmqFWyT5d9/LeYCd7E3scv3qQOkAZQDiwOgbyxZOQ=
after_success:
  - "openssl aes-256-cbc -k '$DEPLOY_KEY' -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa"
  - "[[ $TRAVIS_BRANCH = 'master' ]] && bundle exec cap production deploy"

